del /Q ".\app.syso"
SET CGO_ENABLED=0
SET GOOS=android
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\LeapTun_amd64"
SET GOOS=android
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\LeapTun_arm"
SET GOOS=android
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\LeapTun_arm64"
SET GOOS=darwin
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\darwin\LeapTun_amd64"
SET GOOS=darwin
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\darwin\LeapTun_arm64"
SET GOOS=linux
SET GOARCH=386
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_386"
SET GOOS=linux
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_amd64"
SET GOOS=linux
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_arm"
SET GOOS=linux
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_arm64"
SET GOOS=linux
SET GOARCH=mips
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_mips"
SET GOOS=linux
SET GOARCH=mips64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_mips64"
SET GOOS=linux
SET GOARCH=mips64le
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_mips64le"
SET GOOS=linux
SET GOARCH=mipsle
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_mipsle"
SET GOOS=linux
SET GOARCH=ppc64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_ppc64"
SET GOOS=linux
SET GOARCH=ppc64le
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_ppc64le"
SET GOOS=linux
SET GOARCH=riscv64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_riscv64"
SET GOOS=linux
SET GOARCH=s390x
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\LeapTun_s390x"
SET GOOS=windows
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\LeapTun_arm64.exe"
copy /Y "windows\app.syso" "."
SET GOOS=windows
SET GOARCH=386
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\LeapTun_386.exe"
SET GOOS=windows
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\LeapTun_arm.exe "
SET GOOS=windows
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\LeapTun_amd64.exe"
pause
